import { IDeaerator } from '../../types/data-types';

const deaeratorsData: IDeaerator[] = [
  {
    id: 0,
    name: 'ДА-5/2',
    performance: 5,
    performanceDiapason: '1.5-6',
    pressure: 0.02,
    temperature: 104.25,
    averageWaterHeating: '10-50',
    tankType: 'БДА-2',
    tankCapacity: 2,
    evaporationType: 'ОВА-2',
    evaporationArea: 2,
    safetyDevice: 'ДА-25',
    link: 'https://ds22.su/deaerator-da-52',
  },
  {
    id: 1,
    name: 'ДА-5/4',
    performance: 5,
    performanceDiapason: '1.5-6',
    pressure: 0.02,
    temperature: 104.25,
    averageWaterHeating: '10-50',
    tankType: 'БДА-4',
    tankCapacity: 4,
    evaporationType: 'ОВА-2',
    evaporationArea: 2,
    safetyDevice: 'ДА-25',
    link: 'https://ds22.su/deaerator-da-54',
  },
  {
    id: 2,
    name: 'ДА-15/4',
    performance: 15,
    performanceDiapason: '4.5-18',
    pressure: 0.02,
    temperature: 104.25,
    averageWaterHeating: '10-50',
    tankType: 'БДА-4',
    tankCapacity: 4,
    evaporationType: 'ОВА-2',
    evaporationArea: 2,
    safetyDevice: 'ДА-25',
    link: 'https://ds22.su/deaerator-da-154',
  },
  {
    id: 3,
    name: 'ДА-15/8',
    performance: 15,
    performanceDiapason: '4.5-18',
    pressure: 0.02,
    temperature: 104.25,
    averageWaterHeating: '10-50',
    tankType: 'БДА-8',
    tankCapacity: 8,
    evaporationType: 'ОВА-2',
    evaporationArea: 2,
    safetyDevice: 'ДА-25',
    link: 'https://ds22.su/deaerator-da-158',
  },
  {
    id: 4,
    name: 'ДА-25/4',
    performance: 15,
    performanceDiapason: '7.5-30',
    pressure: 0.02,
    temperature: 104.25,
    averageWaterHeating: '10-50',
    tankType: 'БДА-8',
    tankCapacity: 8,
    evaporationType: 'ОВА-2',
    evaporationArea: 2,
    safetyDevice: 'ДА-25',
    link: 'https://ds22.su/deaerator-da-258',
  },
  {
    id: 5,
    name: 'ДА-25/15',
    performance: 25,
    performanceDiapason: '7.5-30',
    pressure: 0.02,
    temperature: 104.25,
    averageWaterHeating: '10-50',
    tankType: 'БДА-15',
    tankCapacity: 15,
    evaporationType: 'ОВА-2',
    evaporationArea: 2,
    safetyDevice: 'ДА-25',
    link: 'https://ds22.su/deaerator-da-2515',
  },
  {
    id: 6,
    name: 'ДА-50/15',
    performance: 50,
    performanceDiapason: '30-120',
    pressure: 0.02,
    temperature: 104.25,
    averageWaterHeating: '10-50',
    tankType: 'БДА-15',
    tankCapacity: 15,
    evaporationType: 'ОВА-2',
    evaporationArea: 2,
    safetyDevice: 'ДА-50',
    link: 'https://ds22.su/deaerator-da-5015',
  },
  {
    id: 7,
    name: 'ДА-100/25',
    performance: 100,
    performanceDiapason: '30-120',
    pressure: 0.02,
    temperature: 104.25,
    averageWaterHeating: '10-50',
    tankType: 'БДА-25',
    tankCapacity: 25,
    evaporationType: 'ОВА-8',
    evaporationArea: 8,
    safetyDevice: 'ДА-100',
    link: 'https://ds22.su/deaerator-da-10025',
  },
  {
    id: 8,
    name: 'ДА-100/35',
    performance: 100,
    performanceDiapason: '30-120',
    pressure: 0.02,
    temperature: 104.25,
    averageWaterHeating: '10-50',
    tankType: 'БДА-35',
    tankCapacity: 35,
    evaporationType: 'ОВА-8',
    evaporationArea: 8,
    safetyDevice: 'ДА-100',
    link: 'https://ds22.su/deaerator-da-10035',
  },
  {
    id: 9,
    name: 'ДА-200/50',
    performance: 200,
    performanceDiapason: '60-240',
    pressure: 0.02,
    temperature: 104.25,
    averageWaterHeating: '10-50',
    tankType: 'БДА-50',
    tankCapacity: 50,
    evaporationType: 'ОВА-16',
    evaporationArea: 16,
    safetyDevice: 'ДА-200',
    link: 'https://dlyakotlov.ru/catalog/kotelnoe-oborudovanie/deaeratory-atmosfernye',
  },
  {
    id: 10,
    name: 'ДА-300/75',
    performance: 300,
    performanceDiapason: '90-360',
    pressure: 0.02,
    temperature: 104.25,
    averageWaterHeating: '10-50',
    tankType: 'БДА-75',
    tankCapacity: 75,
    evaporationType: 'ОВА-25',
    evaporationArea: 25,
    safetyDevice: 'ДА-300',
    link: 'https://dlyakotlov.ru/catalog/kotelnoe-oborudovanie/deaeratory-atmosfernye',
  },
];

export default deaeratorsData;
