import { IFilter } from '../../types/data-types';

const LightFiltersData: IFilter[] = [
  {
    id: 0,
    name: 'ФОВ-0,7-0,6',
    pressure: 0.6,
    diameter: 700,
    performance: 3,
    filtrationHeight: 1,
    filtrationArea: 0.39,
    filterLoadSize: 0.45,
    link: 'https://ds22.su/filtr-fov-07-06',
  },
  {
    id: 1,
    name: 'ФОВ-1,0-0,6',
    pressure: 0.6,
    diameter: 1000,
    performance: 12,
    filtrationHeight: 1,
    filtrationArea: 0.76,
    filterLoadSize: 0.95,
    link: 'https://ds22.su/filtr-osvetitelnyj-fov-10-06',
  },
  {
    id: 2,
    name: 'ФОВ-1,4-0,6',
    pressure: 0.6,
    diameter: 1400,
    performance: 16,
    filtrationHeight: 1,
    filtrationArea: 1.54,
    filterLoadSize: 1.88,
    link: 'https://ds22.su/filtr-osvetitelnyj-fov-14-06',
  },
  {
    id: 3,
    name: 'ФОВ-1,5-0,6',
    pressure: 0.6,
    diameter: 1500,
    performance: 20,
    filtrationHeight: 1,
    filtrationArea: 1.72,
    filterLoadSize: 1.76,
    link: 'https://ds22.su/filtr-osvetitelnyj-fov-15-06',
  },
  {
    id: 4,
    name: 'ФОВ-2,0-0,6',
    pressure: 0.6,
    diameter: 2000,
    performance: 30,
    filtrationHeight: 1,
    filtrationArea: 3.1,
    filterLoadSize: 4.3,
    link: 'https://ds22.su/filtr-osvetitelnyj-fov-20-06',
  },
  {
    id: 5,
    name: 'ФОВ-2,6-0,6',
    pressure: 0.6,
    diameter: 2600,
    performance: 50,
    filtrationHeight: 1,
    filtrationArea: 5.2,
    filterLoadSize: 7.9,
    link: 'https://ds22.su/filtr-osvetitelnyj-fov-26-06',
  },
  {
    id: 6,
    name: 'ФОВ-3,0-0,6',
    pressure: 0.6,
    diameter: 3000,
    performance: 70,
    filtrationHeight: 1,
    filtrationArea: 6.95,
    filterLoadSize: 11,
    link: 'https://ds22.su/filtr-osvetitelnyj-fov-30-06',
  },
  {
    id: 7,
    name: 'ФОВ-3,4-0,6',
    pressure: 0.6,
    diameter: 3000,
    performance: 90,
    filtrationHeight: 1,
    filtrationArea: 9.1,
    filterLoadSize: 14.7,
    link: 'https://ds22.su/filtr-osvetitelnyj-fov-34-06',
  },
];

export default LightFiltersData;
